[package]
name = "pdf_data_extractor"
version = "0.2.0"
edition = "2024"

[dependencies]
rust_xlsxwriter = "0.84.0"
clap = { version = "4.5.31", features = ["derive"] }
pdf-extract = "0.8.2"
regex = "1.11.1"

